export const opticIds = ['optic_1x', 'optic_2x', 'optic_3x', 'optic_4x', 'optic_6x', 'optic_8x', 'optic_10x', 'optic_seer_passive'] as const;
export const controllerNumericOpticIds = ['controller_ads_sensitivity', 'controller_numeric_optic_2x', 'controller_numeric_optic_3x', 'controller_numeric_optic_4x', 'controller_numeric_optic_6x', 'controller_numeric_optic_8x', 'controller_numeric_optic_10x', 'controller_numeric_optic_seer_passive'] as const;
export const controllerAdvancedOpticIds = ['controller_alc_optic_1x', 'controller_alc_optic_2x', 'controller_alc_optic_3x', 'controller_alc_optic_4x', 'controller_alc_optic_6x', 'controller_alc_optic_8x', 'controller_alc_optic_10x', 'controller_alc_optic_seer_passive'] as const;
export const controllerAlcRows: { id: string; min: number; max: number; step: number; unit?: '%' }[] = [
  {id:'controller_alc_deadzone',min:0,max:0.5,step:0.01,unit:'%'},
  {id:'controller_alc_outer_threshold',min:0.01,max:0.3,step:0.01,unit:'%'},
  {id:'controller_alc_curve',min:0,max:30,step:1},
  {id:'controller_alc_yaw',min:0,max:500,step:1},
  {id:'controller_alc_pitch',min:0,max:500,step:1},
  {id:'controller_alc_extra_yaw',min:0,max:250,step:1},
  {id:'controller_alc_extra_pitch',min:0,max:250,step:1},
  {id:'controller_alc_ramp_time',min:0,max:1,step:0.01,unit:'%'},
  {id:'controller_alc_ramp_delay',min:0,max:1,step:0.01,unit:'%'},
  {id:'controller_alc_ads_yaw',min:0,max:500,step:1},
  {id:'controller_alc_ads_pitch',min:0,max:500,step:1},
  {id:'controller_alc_ads_extra_yaw',min:0,max:250,step:1},
  {id:'controller_alc_ads_extra_pitch',min:0,max:250,step:1},
  {id:'controller_alc_ads_ramp_time',min:0,max:1,step:0.01,unit:'%'},
  {id:'controller_alc_ads_ramp_delay',min:0,max:1,step:0.01,unit:'%'},
];

export const hudIds = [
  'hud_minimap_rotate', 'hud_button_hints', 'hud_enemy_health', 'hud_enemy_highlight',
  'hud_hopup', 'hud_obituary', 'hud_tips', 'hud_streamer', 'hud_ping_double',
  'anonymous_mode', 'chain_heal', 'show_weapon_flyouts', 'show_offscreen_portrait',
  'show_team_names_map', 'show_level_up', 'show_callsigns', 'show_meter'
] as const;

export const gameplayIds = ['auto_sprint', 'hold_sprint', 'close_deathbox_on_damage', 'auto_cycle_empty', 'death_hints'] as const;
export const audioAccessibilityIds = ['subtitles', 'text_to_speech', 'speech_to_text'] as const;

export const controllerIds = [
  'controller_invert', 'controller_rumble', 'controller_southpaw',
  'controller_toggle_ads', 'controller_custom_aim', 'controller_per_optic_ads'
] as const;

export const audioVolumeIds = [
  'audio_master', 'audio_dialogue', 'audio_music_game', 'audio_music_lobby',
  'audio_sfx', 'audio_voice'
] as const;

export const labels: Record<string, [string, string]> = {
  auto_run: ['オートラン','Auto Run'], jetpack_toggle: ['ジェットパック/滑空操作','Jetpack / Glide Control'],
  energy_ammo_percent: ['エネルギーアモの表示','Energy Ammo Display'],
  arsenal_icons: ['アーセナルマップ+HUDアイコン','Arsenal Map and HUD Icons'],
  mantle_input_observed: ['マントルブーストの操作切り替え','Mantle Boost Input'],
  mantle_ui_observed: ['マントルブーストUI','Mantle Boost UI'],
  tutorial_observed: ['チュートリアルシステム','Tutorial System'],
  ping_opacity: ['ピン透明度','Ping Transparency'], performance_display: ['パフォーマンス表示','Performance Display'],
  laser_customized: ['レーザーサイト','Laser Sight'], sprint_view_shake: ['スプリント時の視点のゆれ','Sprint View Shake'],
  spot_shadow_upres: ['スポットシャドウの解像度倍率','Spot Shadow Resolution Factor'],
  anti_aliasing: ['アンチエイリアス','Anti-aliasing'], dynamic_spot_shadows: ['ダイナミックスポットシャドウ','Dynamic Spot Shadows'],
  audio_mix: ['オーディオミックス','Audio Mix'],
  reflex_enabled: ['NVIDIA Reflex','NVIDIA Reflex'], reflex_boost: ['NVIDIA Reflex ブースト','NVIDIA Reflex Boost'],
  fire_mode: ['射撃モード切り替え','Toggle Fire Mode'], survival_item: ['サバイバルアイテムを装備','Equip Survival Item'],
  character_utility: ['キャラクターのユーティリティーアクション','Character Utility Action'],
  legend_wheel: ['レジェンドアップグレード/エモートホイール/ありがとう','Legend Upgrade / Emote Wheel / Thank You'],
  hud: ['HUD', 'HUD'], audio: ['音声', 'Audio'], controller: ['コントローラー', 'Controller'],
  optic_1x: ['1倍スコープ', '1× optic'], optic_2x: ['2倍スコープ', '2× optic'],
  optic_3x: ['3倍スコープ', '3× optic'], optic_4x: ['4倍スコープ', '4× optic'],
  optic_6x: ['6倍スコープ', '6× optic'], optic_8x: ['8倍スコープ', '8× optic'],
  optic_10x: ['10倍スコープ', '10× optic'],
  optic_seer_passive: ['シアのパッシブ感度', 'Seer Passive Sensitivity'],
  mouse_acceleration: ['マウス加速', 'Mouse Acceleration'], invert_mouse: ['マウスY軸反転', 'Invert Mouse Y'],
  mouse_clamp: ['マウスカーソルをゲーム画面に固定', 'Constrain Mouse Cursor to Game'],
  lighting_effects: ['ライティングエフェクト', 'Lighting Effects'],
  hold_sprint: ['長押しでスプリント', 'Hold to Sprint'],
  close_deathbox_on_damage: ['被弾時にデスボックスを閉じる', 'Close Death Box on Damage'],
  fullscreen: ['フルスクリーン', 'Fullscreen'], anisotropic: ['異方性フィルタリング', 'Anisotropic Filtering'],
  borderless: ['ボーダーレス表示', 'Borderless Display'],
  shadows: ['シャドウ', 'Shadows'], volumetric_lighting: ['ボリュームライト', 'Volumetric Lighting'],
  volumetric_fog: ['ボリュームフォグ', 'Volumetric Fog'], adaptive_resolution: ['動的解像度', 'Adaptive Resolution'],
  hud_minimap_rotate: ['ミニマップ回転', 'Minimap Rotation'], hud_button_hints: ['ボタンヒント', 'Button Hints'],
  hud_enemy_health: ['敵の体力バー', 'Enemy Health Bar'], hud_enemy_highlight: ['敵のハイライト', 'Enemy Highlight'],
  hud_hopup: ['ホップアップ通知', 'Hop-up Notification'], hud_obituary: ['キルログ', 'Kill Feed'],
  hud_tips: ['ヒント表示', 'Tips'], hud_streamer: ['配信者モード', 'Streamer Mode'],
  hud_ping_double: ['ダブルタップで敵ピン', 'Double Tap Enemy Ping'],
  auto_cycle_empty: ['弾切れ時に武器を自動切替', 'Auto Cycle Weapon on Empty'],
  death_hints: ['デスヒント', 'Death Hints'],
  ability_fov_scaling: ['アビリティによる視野角変更を無効化', 'Disable Ability FOV Scaling'],
  subtitles: ['字幕', 'Subtitles'],
  text_to_speech: ['チャットの読み上げ', 'Text to Speech'],
  speech_to_text: ['音声の文字起こし', 'Speech to Text'],
  anonymous_mode: ['匿名モード', 'Anonymous Mode'],
  chain_heal: ['連続回復', 'Chain Heal'],
  show_weapon_flyouts: ['武器の情報表示', 'Weapon Flyouts'],
  show_offscreen_portrait: ['画面外の味方ポートレート', 'Offscreen Portraits'],
  show_team_names_map: ['マップ上のチーム名', 'Team Names on Map'],
  show_level_up: ['レベルアップ通知', 'Level Up Notification'],
  show_callsigns: ['コールサイン表示', 'Callsigns'],
  show_meter: ['メーター表示', 'Meter Display'],
  move_forward: ['前進', 'Move Forward'], move_back: ['後退', 'Move Back'],
  move_left: ['左へ移動', 'Move Left'], move_right: ['右へ移動', 'Move Right'],
  equip_weapon_1: ['武器1を装備', 'Equip Weapon 1'], equip_weapon_2: ['武器2を装備', 'Equip Weapon 2'],
  holster_weapon: ['武器を収める', 'Holster Weapons'],
  audio_master: ['マスター音量', 'Master Volume'], audio_dialogue: ['会話音量', 'Dialogue Volume'],
  audio_music_game: ['ゲーム中の音楽', 'In-game Music'], audio_music_lobby: ['ロビーの音楽', 'Lobby Music'],
  audio_sfx: ['効果音', 'Sound Effects'], audio_voice: ['ボイスチャット音量', 'Voice Chat Volume'],
  audio_focus: ['非アクティブ時も再生', 'Play Audio in Background'],
  audio_reduced_music: ['音楽を控えめにする', 'Reduce Music'], voice_enabled: ['ボイスチャット', 'Voice Chat'],
  controller_invert: ['コントローラーY軸反転', 'Invert Controller Y'],
  controller_rumble: ['振動', 'Vibration'], controller_southpaw: ['サウスポー', 'Southpaw'],
  controller_toggle_ads: ['ADS切替', 'Toggle ADS'], controller_custom_aim: ['詳細なエイム設定', 'Advanced Aim Settings'],
  controller_per_optic_ads: ['スコープ別ADS設定', 'Per-optic ADS Settings'],
  controller_button_layout: ['ボタン配置', 'Button Layout'],
  controller_stick_layout: ['スティック配置', 'Stick Layout'],
  controller_interact_mode: ['アクション/リロードボタン', 'Interact / Reload Button'],
  controller_crouch_hold: ['しゃがみボタン', 'Crouch Button'],
  controller_survival_slot: ['サバイバルスロットボタン', 'Survival Slot Button'],
  controller_adaptive_trigger: ['アダプティブトリガー', 'Adaptive Trigger'],
  controller_trigger_deadzone: ['トリガーのデッドゾーン', 'Trigger Deadzone'],
  controller_cursor_speed: ['メニューカーソルの速度', 'Menu Cursor Speed'],
  controller_look_sensitivity: ['視点感度', 'Look Sensitivity'],
  controller_ads_sensitivity: ['視点感度（エイム時）', 'Look Sensitivity (ADS)'],
  controller_response_curve: ['反応曲線', 'Response Curve'],
  controller_look_deadzone: ['視点操作デッドゾーン', 'Look Deadzone'],
  controller_move_deadzone: ['移動スティックのデッドゾーン', 'Movement Deadzone'],
  controller_alc_deadzone: ['デッドゾーン', 'Deadzone'], controller_alc_outer_threshold: ['入力範囲の限界', 'Outer Threshold'],
  controller_alc_curve: ['反応曲線', 'Response Curve'],
  controller_alc_yaw: ['左右視点移動速度', 'Yaw Speed'], controller_alc_pitch: ['上下視点移動速度', 'Pitch Speed'],
  controller_alc_extra_yaw: ['左右視点移動加速', 'Turning Extra Yaw'], controller_alc_extra_pitch: ['上下視点移動加速', 'Turning Extra Pitch'],
  controller_alc_ramp_time: ['視点移動付与時間', 'Turning Ramp-up Time'], controller_alc_ramp_delay: ['視点移動付与ディレイ', 'Turning Ramp-up Delay'],
  controller_alc_ads_yaw: ['左右視点移動速度（エイム時）', 'ADS Yaw Speed'], controller_alc_ads_pitch: ['上下視点移動速度（エイム時）', 'ADS Pitch Speed'],
  controller_alc_ads_extra_yaw: ['左右視点移動加速（エイム時）', 'ADS Turning Extra Yaw'], controller_alc_ads_extra_pitch: ['上下視点移動加速（エイム時）', 'ADS Turning Extra Pitch'],
  controller_alc_ads_ramp_time: ['視点移動付与時間（エイム時）', 'ADS Turning Ramp-up Time'], controller_alc_ads_ramp_delay: ['視点移動付与ディレイ（エイム時）', 'ADS Turning Ramp-up Delay'],
  controller_alc_target_compensation: ['ターゲット補正', 'Target Compensation'], controller_alc_melee_compensation: ['格闘ターゲット補正', 'Melee Target Compensation'],
  controller_alc_per_optic: ['スコープ倍率エイム感度', 'Per-optic ADS Sensitivity'],
  ...Object.fromEntries(['1x','2x','3x','4x','6x','8x','10x','seer_passive'].flatMap((optic,index) => [
    [`controller_alc_optic_${optic}`, optic==='seer_passive'?['シアのパッシブ','Seer Passive']:optic==='1x'?['1倍スコープ/アイアンサイト','1× Optic / Iron Sights']:[`${optic.slice(0,-1)}倍スコープ`,`${optic.slice(0,-1)}× Optic`]],
    ...(index===0?[]:[[`controller_numeric_optic_${optic}`, optic==='seer_passive'?['シアのパッシブ','Seer Passive']:[`${optic.slice(0,-1)}倍スコープ`,`${optic.slice(0,-1)}× Optic`]]]),
  ])) as Record<string,[string,string]>,
  crouch_toggle: ['しゃがみ切替', 'Toggle Crouch'], crouch_hold: ['しゃがみ長押し', 'Hold Crouch'],
  sprint: ['スプリント', 'Sprint'], attack: ['射撃', 'Fire'], aim: ['エイム', 'Aim'],
  inventory: ['インベントリ', 'Inventory'], map: ['マップ', 'Map'], grenade: ['グレネード', 'Grenade'],
  tactical: ['戦術アビリティ', 'Tactical Ability'], ultimate: ['アルティメット', 'Ultimate Ability'],
  inspect_weapon: ['武器の確認', 'Inspect Weapon'], weapon_cycle: ['武器切替', 'Cycle Weapons'],
  push_to_talk: ['プッシュトゥトーク', 'Push to Talk'],
  optic_heading: ['スコープ別感度', 'Per-optic Sensitivity'],
  optic_hint: ['1.00が標準倍率です。変更は「適用」するまで保存されません。', '1.00 is the default multiplier. Changes stay pending until Apply.'],
  reset_optics: ['すべて1.00に戻す', 'Reset all to 1.00'],
  copy_optic: ['1倍の値をすべてにコピー', 'Copy 1× to all'],
  more_settings: ['追加設定', 'More settings'],
  refresh: ['再読込', 'Reload'],
  volume_percent: ['音量', 'Volume'],
};
